onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /axi4_tb/vif/ARVALID
add wave -noupdate /axi4_tb/vif/ARREADY
add wave -noupdate /axi4_tb/vif/ARADDR
add wave -noupdate /axi4_tb/vif/ARSIZE
add wave -noupdate /axi4_tb/vif/ARLEN
add wave -noupdate /axi4_tb/vif/ACLK
add wave -noupdate /axi4_tb/vif/ARESETn
add wave -noupdate /axi4_tb/vif/AWADDR
add wave -noupdate /axi4_tb/vif/AWLEN
add wave -noupdate /axi4_tb/vif/AWSIZE
add wave -noupdate /axi4_tb/vif/AWVALID
add wave -noupdate /axi4_tb/vif/AWREADY
add wave -noupdate /axi4_tb/vif/WDATA
add wave -noupdate /axi4_tb/vif/WLAST
add wave -noupdate /axi4_tb/vif/WVALID
add wave -noupdate /axi4_tb/vif/WREADY
add wave -noupdate /axi4_tb/vif/BRESP
add wave -noupdate /axi4_tb/vif/BVALID
add wave -noupdate /axi4_tb/vif/BREADY
add wave -noupdate /axi4_tb/vif/RDATA
add wave -noupdate /axi4_tb/vif/RRESP
add wave -noupdate /axi4_tb/vif/RLAST
add wave -noupdate /axi4_tb/vif/RVALID
add wave -noupdate /axi4_tb/vif/RREADY
add wave -noupdate /axi4_tb/DUT/ACLK
add wave -noupdate /axi4_tb/DUT/ARESETn
add wave -noupdate /axi4_tb/DUT/AWADDR
add wave -noupdate /axi4_tb/DUT/AWLEN
add wave -noupdate /axi4_tb/DUT/AWSIZE
add wave -noupdate /axi4_tb/DUT/AWVALID
add wave -noupdate /axi4_tb/DUT/AWREADY
add wave -noupdate /axi4_tb/DUT/WDATA
add wave -noupdate /axi4_tb/DUT/WVALID
add wave -noupdate /axi4_tb/DUT/WLAST
add wave -noupdate /axi4_tb/DUT/WREADY
add wave -noupdate /axi4_tb/DUT/BRESP
add wave -noupdate /axi4_tb/DUT/BVALID
add wave -noupdate /axi4_tb/DUT/BREADY
add wave -noupdate /axi4_tb/DUT/ARADDR
add wave -noupdate /axi4_tb/DUT/ARLEN
add wave -noupdate /axi4_tb/DUT/ARSIZE
add wave -noupdate /axi4_tb/DUT/ARVALID
add wave -noupdate /axi4_tb/DUT/ARREADY
add wave -noupdate /axi4_tb/DUT/RDATA
add wave -noupdate /axi4_tb/DUT/RRESP
add wave -noupdate /axi4_tb/DUT/RVALID
add wave -noupdate /axi4_tb/DUT/RLAST
add wave -noupdate /axi4_tb/DUT/RREADY
add wave -noupdate /axi4_tb/DUT/mem_en
add wave -noupdate /axi4_tb/DUT/mem_we
add wave -noupdate /axi4_tb/DUT/mem_addr
add wave -noupdate /axi4_tb/DUT/mem_wdata
add wave -noupdate /axi4_tb/DUT/mem_rdata
add wave -noupdate /axi4_tb/DUT/write_addr
add wave -noupdate /axi4_tb/DUT/read_addr
add wave -noupdate /axi4_tb/DUT/write_burst_len
add wave -noupdate /axi4_tb/DUT/read_burst_len
add wave -noupdate /axi4_tb/DUT/write_burst_cnt
add wave -noupdate /axi4_tb/DUT/read_burst_cnt
add wave -noupdate /axi4_tb/DUT/write_size
add wave -noupdate /axi4_tb/DUT/read_size
add wave -noupdate /axi4_tb/DUT/write_addr_incr
add wave -noupdate /axi4_tb/DUT/read_addr_incr
add wave -noupdate /axi4_tb/DUT/write_boundary_cross
add wave -noupdate /axi4_tb/DUT/read_boundary_cross
add wave -noupdate /axi4_tb/DUT/write_addr_valid
add wave -noupdate /axi4_tb/DUT/read_addr_valid
add wave -noupdate /axi4_tb/DUT/write_state
add wave -noupdate /axi4_tb/DUT/read_state
add wave -noupdate /axi4_tb/DUT/mem_rdata_reg
add wave -noupdate /axi4_tb/DUT/mem_inst/clk
add wave -noupdate /axi4_tb/DUT/mem_inst/rst_n
add wave -noupdate /axi4_tb/DUT/mem_inst/mem_en
add wave -noupdate /axi4_tb/DUT/mem_inst/mem_we
add wave -noupdate /axi4_tb/DUT/mem_inst/mem_addr
add wave -noupdate /axi4_tb/DUT/mem_inst/mem_wdata
add wave -noupdate /axi4_tb/DUT/mem_inst/mem_rdata
add wave -noupdate /axi4_tb/DUT/mem_inst/j
add wave -noupdate /axi4_tb/check/vif/ACLK
add wave -noupdate /axi4_tb/check/vif/ARESETn
add wave -noupdate /axi4_tb/check/vif/AWADDR
add wave -noupdate /axi4_tb/check/vif/AWLEN
add wave -noupdate /axi4_tb/check/vif/AWSIZE
add wave -noupdate /axi4_tb/check/vif/AWVALID
add wave -noupdate /axi4_tb/check/vif/AWREADY
add wave -noupdate /axi4_tb/check/vif/WDATA
add wave -noupdate /axi4_tb/check/vif/WLAST
add wave -noupdate /axi4_tb/check/vif/WVALID
add wave -noupdate /axi4_tb/check/vif/WREADY
add wave -noupdate /axi4_tb/check/vif/BRESP
add wave -noupdate /axi4_tb/check/vif/BVALID
add wave -noupdate /axi4_tb/check/vif/BREADY
add wave -noupdate /axi4_tb/check/vif/ARADDR
add wave -noupdate /axi4_tb/check/vif/ARLEN
add wave -noupdate /axi4_tb/check/vif/ARSIZE
add wave -noupdate /axi4_tb/check/vif/ARVALID
add wave -noupdate /axi4_tb/check/vif/ARREADY
add wave -noupdate /axi4_tb/check/vif/RDATA
add wave -noupdate /axi4_tb/check/vif/RRESP
add wave -noupdate /axi4_tb/check/vif/RLAST
add wave -noupdate /axi4_tb/check/vif/RVALID
add wave -noupdate /axi4_tb/check/vif/RREADY
add wave -noupdate /uvm_pkg::uvm_start_uvm_declarations
add wave -noupdate /uvm_pkg::uvm_global_random_seed
add wave -noupdate /uvm_pkg::UVM_UNBOUNDED_CONNECTIONS
add wave -noupdate /uvm_pkg::uvm_hdl_check_path/uvm_hdl_check_path
add wave -noupdate /uvm_pkg::uvm_hdl_deposit/uvm_hdl_deposit
add wave -noupdate /uvm_pkg::uvm_hdl_deposit/value
add wave -noupdate /uvm_pkg::uvm_hdl_force/uvm_hdl_force
add wave -noupdate /uvm_pkg::uvm_hdl_force/value
add wave -noupdate /uvm_pkg::uvm_hdl_force_time/value
add wave -noupdate /uvm_pkg::uvm_hdl_force_time/force_time
add wave -noupdate /uvm_pkg::uvm_hdl_release_and_read/uvm_hdl_release_and_read
add wave -noupdate /uvm_pkg::uvm_hdl_release_and_read/value
add wave -noupdate /uvm_pkg::uvm_hdl_release/uvm_hdl_release
add wave -noupdate /uvm_pkg::uvm_hdl_read/uvm_hdl_read
add wave -noupdate /uvm_pkg::uvm_hdl_read/value
add wave -noupdate /uvm_pkg::uvm_dpi_regexec/uvm_dpi_regexec
add wave -noupdate /uvm_pkg::uvm_re_match/uvm_re_match
add wave -noupdate /uvm_pkg::uvm_radix_to_string/radix
add wave -noupdate /uvm_pkg::uvm_status_container::print_matches
add wave -noupdate /uvm_pkg::uvm_instance_scope/c
add wave -noupdate /uvm_pkg::uvm_instance_scope/pos
add wave -noupdate /uvm_pkg::uvm_oneway_hash/uvm_oneway_hash
add wave -noupdate /uvm_pkg::uvm_oneway_hash/seed
add wave -noupdate /uvm_pkg::uvm_oneway_hash/msb
add wave -noupdate /uvm_pkg::uvm_oneway_hash/current_byte
add wave -noupdate /uvm_pkg::uvm_oneway_hash/crc1
add wave -noupdate /uvm_pkg::uvm_create_random_seed/uvm_create_random_seed
add wave -noupdate /uvm_pkg::uvm_leaf_scope/scope_separator
add wave -noupdate /uvm_pkg::uvm_leaf_scope/bracket_match
add wave -noupdate /uvm_pkg::uvm_leaf_scope/pos
add wave -noupdate /uvm_pkg::uvm_leaf_scope/bmatches
add wave -noupdate /uvm_pkg::uvm_vector_to_string/value
add wave -noupdate /uvm_pkg::uvm_vector_to_string/size
add wave -noupdate /uvm_pkg::uvm_vector_to_string/radix
add wave -noupdate /uvm_pkg::uvm_get_array_index_int/uvm_get_array_index_int
add wave -noupdate /uvm_pkg::uvm_get_array_index_int/is_wildcard
add wave -noupdate /uvm_pkg::uvm_get_array_index_int/i
add wave -noupdate /uvm_pkg::uvm_get_array_index_string/is_wildcard
add wave -noupdate /uvm_pkg::uvm_get_array_index_string/i
add wave -noupdate /uvm_pkg::uvm_is_array/uvm_is_array
add wave -noupdate /uvm_pkg::uvm_object::use_uvm_seeding
add wave -noupdate /uvm_pkg::uvm_object::m_inst_count
add wave -noupdate /uvm_pkg::uvm_object::copy/depth
add wave -noupdate /uvm_pkg::uvm_object::compare/style
add wave -noupdate /uvm_pkg::uvm_factory::m_debug_pass
add wave -noupdate /uvm_pkg::uvm_resource_options::auditing
add wave -noupdate /uvm_pkg::uvm_resource_base::default_precedence
add wave -noupdate /uvm_pkg::uvm_resource_pool::m_has_wildcard_names
add wave -noupdate /uvm_pkg::uvm_resource_db_options::ready
add wave -noupdate /uvm_pkg::uvm_resource_db_options::tracing
add wave -noupdate /uvm_pkg::uvm_config_db_options::ready
add wave -noupdate /uvm_pkg::uvm_config_db_options::tracing
add wave -noupdate /uvm_pkg::uvm_recorder::handle
add wave -noupdate /uvm_pkg::uvm_callbacks_base::m_tracing
add wave -noupdate /uvm_pkg::uvm_report_catcher::m_register_cb_uvm_report_catcher
add wave -noupdate /uvm_pkg::uvm_report_catcher::m_modified_severity
add wave -noupdate /uvm_pkg::uvm_report_catcher::m_modified_verbosity
add wave -noupdate /uvm_pkg::uvm_report_catcher::m_line_number
add wave -noupdate /uvm_pkg::uvm_report_catcher::m_modified_action
add wave -noupdate /uvm_pkg::uvm_report_catcher::m_set_action_called
add wave -noupdate /uvm_pkg::uvm_report_catcher::m_demoted_fatal
add wave -noupdate /uvm_pkg::uvm_report_catcher::m_demoted_error
add wave -noupdate /uvm_pkg::uvm_report_catcher::m_demoted_warning
add wave -noupdate /uvm_pkg::uvm_report_catcher::m_caught_fatal
add wave -noupdate /uvm_pkg::uvm_report_catcher::m_caught_error
add wave -noupdate /uvm_pkg::uvm_report_catcher::m_caught_warning
add wave -noupdate /uvm_pkg::uvm_report_catcher::DO_NOT_CATCH
add wave -noupdate /uvm_pkg::uvm_report_catcher::DO_NOT_MODIFY
add wave -noupdate /uvm_pkg::uvm_report_catcher::m_debug_flags
add wave -noupdate /uvm_pkg::uvm_report_catcher::m_orig_severity
add wave -noupdate /uvm_pkg::uvm_report_catcher::m_orig_action
add wave -noupdate /uvm_pkg::uvm_report_catcher::m_orig_verbosity
add wave -noupdate /uvm_pkg::uvm_report_catcher::do_report
add wave -noupdate /uvm_pkg::uvm_report_catcher::process_all_report_catchers/in_catcher
add wave -noupdate /uvm_pkg::uvm_report_handler::m_relnotes_done
add wave -noupdate /uvm_pkg::uvm_phase::m_phase_trace
add wave -noupdate /uvm_pkg::uvm_phase::m_use_ovm_run_semantic
add wave -noupdate /uvm_pkg::uvm_phase::m_print_successors/level
add wave -noupdate /uvm_pkg::uvm_component::m_config_set
add wave -noupdate /uvm_pkg::uvm_component::print_config_matches
add wave -noupdate /uvm_pkg::uvm_component::print_config_settings/have_been_warned
add wave -noupdate /uvm_pkg::uvm_component::m_set_cl_verb/first
add wave -noupdate /uvm_pkg::uvm_component::m_set_cl_sev/first
add wave -noupdate /uvm_pkg::uvm_root::set_timeout/m_uvm_timeout_overridable
add wave -noupdate /uvm_pkg::uvm_callbacks_objection::m_register_cb_uvm_objection_callback
add wave -noupdate /uvm_pkg::set_global_timeout/timeout
add wave -noupdate /uvm_pkg::set_global_timeout/overridable
add wave -noupdate /uvm_pkg::set_global_stop_timeout/timeout
add wave -noupdate /uvm_pkg::uvm_report_enabled/uvm_report_enabled
add wave -noupdate /uvm_pkg::uvm_report_enabled/verbosity
add wave -noupdate /uvm_pkg::uvm_report_enabled/severity
add wave -noupdate /uvm_pkg::uvm_report/severity
add wave -noupdate /uvm_pkg::uvm_report/verbosity
add wave -noupdate /uvm_pkg::uvm_report/line
add wave -noupdate /uvm_pkg::uvm_report_info/verbosity
add wave -noupdate /uvm_pkg::uvm_report_info/line
add wave -noupdate /uvm_pkg::uvm_report_warning/verbosity
add wave -noupdate /uvm_pkg::uvm_report_warning/line
add wave -noupdate /uvm_pkg::uvm_report_error/verbosity
add wave -noupdate /uvm_pkg::uvm_report_error/line
add wave -noupdate /uvm_pkg::uvm_report_fatal/verbosity
add wave -noupdate /uvm_pkg::uvm_report_fatal/line
add wave -noupdate /uvm_pkg::uvm_string_to_severity/uvm_string_to_severity
add wave -noupdate /uvm_pkg::uvm_string_to_severity/sev
add wave -noupdate /uvm_pkg::set_config_int/value
add wave -noupdate /uvm_pkg::set_config_object/clone
add wave -noupdate /uvm_pkg::uvm_is_match/uvm_is_match
add wave -noupdate /uvm_pkg::uvm_wait_for_nba_region/nba
add wave -noupdate /uvm_pkg::uvm_wait_for_nba_region/next_nba
add wave -noupdate /uvm_pkg::uvm_sequence_item::issued1
add wave -noupdate /uvm_pkg::uvm_sequence_item::issued2
add wave -noupdate /uvm_pkg::uvm_sequencer_base::g_request_id
add wave -noupdate /uvm_pkg::uvm_sequencer_base::g_sequence_id
add wave -noupdate /uvm_pkg::uvm_sequencer_base::g_sequencer_id
add wave -noupdate /uvm_pkg::uvm_tlm_time::m_resolution
add wave -noupdate /uvm_pkg::uvm_reg_backdoor::m_register_cb_uvm_reg_cbs
add wave -noupdate /uvm_pkg::uvm_reg_field::m_max_size
add wave -noupdate /uvm_pkg::uvm_reg_field::m_predefined
add wave -noupdate /uvm_pkg::uvm_reg_field::m_register_cb_uvm_reg_cbs
add wave -noupdate /uvm_pkg::uvm_vreg_field::m_register_cb_uvm_vreg_field_cbs
add wave -noupdate /uvm_pkg::uvm_reg::m_max_size
add wave -noupdate /uvm_pkg::uvm_reg::m_register_cb_uvm_reg_cbs
add wave -noupdate /uvm_pkg::uvm_vreg::m_register_cb_uvm_vreg_cbs
add wave -noupdate /uvm_pkg::uvm_mem::m_max_size
add wave -noupdate /uvm_pkg::uvm_mem::m_register_cb_uvm_reg_cbs
add wave -noupdate /uvm_pkg::uvm_reg_block::id
add wave -noupdate /uvm_pkg::uvm_spell_chkr__1::max
add wave -noupdate /questa_uvm_pkg::questa_uvm_recorder::UVM_TR_TRACE_API
add wave -noupdate /questa_uvm_pkg::questa_uvm_recorder::UVM_TR_TRACE_API_DETAIL
add wave -noupdate /questa_uvm_pkg::questa_uvm_recorder::UVM_TR_TRACE_PLI_CALLS
add wave -noupdate /questa_uvm_pkg::questa_uvm_recorder::uvm_tr_initialized
add wave -noupdate /questa_uvm_pkg::questa_configdb::private_getConfigData/save_index
add wave -noupdate /questa_uvm_pkg::questa_configdb::getConfigData/save_start_index
add wave -noupdate /questa_uvm_pkg::questa_configdb::getConfigData/save_buf_size
add wave -noupdate /questa_uvm_pkg::questa_configdb::getConfigDataWithAccesses/var_save_start_index
add wave -noupdate /questa_uvm_pkg::questa_configdb::getConfigDataWithAccesses/var_save_buf_size
add wave -noupdate /questa_uvm_pkg::questa_uvm::is_questa_uvm_pkg_inited
add wave -noupdate /questa_uvm_pkg::questa_uvm::m_phase_monitor_started
add wave -noupdate /questa_uvm_pkg::questa_uvm::m_the_default_setting
add wave -noupdate /questa_uvm_pkg::questa_uvm::major_revision
add wave -noupdate /questa_uvm_pkg::questa_uvm::minor_revision
add wave -noupdate /questa_uvm_pkg::questa_uvm::patch_revision
add wave -noupdate /std::mailbox::mailbox__1::try_put/try_put
add wave -noupdate /std::mailbox::mailbox__1::try_get/try_get
add wave -noupdate /std::mailbox::mailbox__1::try_peek/try_peek
add wave -noupdate /std::mailbox::mailbox__2::try_put/try_put
add wave -noupdate /std::mailbox::mailbox__2::try_get/try_get
add wave -noupdate /std::mailbox::mailbox__2::try_peek/try_peek
add wave -noupdate /std::mailbox::mailbox__3::try_put/try_put
add wave -noupdate /std::mailbox::mailbox__3::try_get/try_get
add wave -noupdate /std::mailbox::mailbox__3::try_peek/try_peek
add wave -noupdate /std::mailbox::mailbox__4::try_put/try_put
add wave -noupdate /std::mailbox::mailbox__4::try_get/try_get
add wave -noupdate /std::mailbox::mailbox__4::try_peek/try_peek
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {106515298 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {106403792 ps} {106634250 ps}
